# Generated by Django 5.0.6 on 2024-05-31 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ETL', '0002_remove_structuredformate_jobtittle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTittle', models.CharField(max_length=200)),
                ('jobDetails', models.CharField(max_length=50000)),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uid_jd', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StructuredFormate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumeName', models.CharField(max_length=150)),
                ('resumeHighlights', models.CharField(max_length=500)),
                ('resumeScore', models.CharField(max_length=150)),
                ('isShared', models.BooleanField(default=False)),
                ('skills', models.CharField(max_length=500)),
                ('contactInfo', models.JSONField()),
                ('experience', models.JSONField()),
                ('others', models.JSONField(max_length=5000)),
                ('project', models.JSONField(max_length=50000)),
                ('education', models.JSONField()),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uid', to=settings.AUTH_USER_MODEL)),
                ('jobTittle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_tittle', to='ETL.jobdescription')),
            ],
        ),
    ]
