"""
Django settings for CV_Ranker project.

Generated by 'django-admin startproject' using Django 5.0.6.

"""

from pathlib import Path
import os
BASE_DIR = Path(__file__).resolve().parent.parent




# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(!1!67zh(tqw%qcj6$%1ocy7koqq$-d)4!a%6^6!xmg6b+d^uj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'django.contrib.sites',
    "Lin_Lou",
    "rest_framework",
    "ETL",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CV_Ranker.urls'


TEMP_DIR = os.path.join(BASE_DIR,"Templates")


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMP_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CV_Ranker.wsgi.application'




DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}



AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]




LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True





STATIC_DIR = os.path.join(BASE_DIR,'static')

STATIC_URL = '/static/'

if DEBUG:
    STATICFILES_DIRS = [STATIC_DIR]
else:
    STATICFILES_ROOT = STATIC_DIR


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




FIREBASE_CONFIG  = {
  "apiKey": "AIzaSyAYUO3JcjV2CK1UDOvudj4Nmzm-kqDs-X0",
  "authDomain": "randomsearch-b73d9.firebaseapp.com",
  "projectId": "randomsearch-b73d9",
  "storageBucket": "randomsearch-b73d9.appspot.com",
  "messagingSenderId": "1071038864705",
  "appId": "1:1071038864705:web:f46274c1f3bc860ea3d5c0",
  "measurementId": "G-GNRVY5H2B2",
  "databaseURL": ""
}



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'hulkmarvadi@gmail.com'
EMAIL_HOST_PASSWORD = 'Hulk@123'
EMAIL_PORT = 587
EMAIL_USE_SSL = False
EMAIL_USE_TLS = True